pipeline{
    agent any
    environment{
        TF_WORKSPACE = "${BRANCH_NAME}"
        TF_IN_AUTOMATION = 'true'
    }
    stages{
        stage('TF init'){
            steps{
                withAWS(){
                    sh 'cd site-s3 && terraform init'
                }
            }
        }

        stage('TF apply'){
            steps{
                sh 'cd site-s3 && terraform apply -auto-approve -var-file="vars_${BRANCH_NAME}.tfvars"'
            }
        }
    }
}