pipeline{
    agent any
    stages{
        stage('Terraform'){
            steps{
                withAWS(){
                    terraform init
                    terraform apply -f -var-file="${vars_file}"
                }
            }
        }
    }
}