pipeline{
    agent any
    environment{
        TF_WORKSPACE = '${workspace}'
        TF_IN_AUTOMATION = 'true'
    }
    stages{
        stage('Switch to folder and TF init'){
            steps{
                withAWS(){
                    sh 'cd weissbeerger-s3/ && terraform init'
                }
            }
        }
        stage('TF apply'){
            steps{
                sh 'terraform apply -auto-approve -var-file="${vars_file}"'
            }
        }
    }
}