pipeline{
    agent any
    stages{
        stage('Terraform'){
            steps{
                withAWS(){
                    sh 'cd weissbeerger-s3/ && terraform init && terraform apply -f -var-file="${vars_file}"'
                }
            }
        }
    }
}